apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- components/test-component--gosg/base
- components/test-component--twbh/base
- components/test-component--zznm/base
kind: Kustomization
resources:
- common-storage-pvc.yaml
